Add devise
limavfabio/MyRailsBlog pull request #9
Opened 2023-05-19 17:48 UTC by limavfabio

This PR adds and configures devise for authentication and authorization capabilities on the app. Notable changes includes:

- Added Login, Registration and Recovery views for user sign up and login
- Ability to confirm email and recover password

2023-05-19 18:27 UTC, franclobo reviewed
Hi @limavfabio, 

![terminator](https://github.com/limavfabio/MyRailsBlog/assets/58642949/cf4fd388-4bd6-4b3d-a550-86f3666520d8)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair-programming project but there aren't commits from your partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-19 23:49 UTC, Felix45 requested changes
Hi @limavfabio , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Devise gem is added correctly to the project :white_check_mark: 
- [x]  Application has email confirmation functionality :white_check_mark: 
- [x] Application allows a user to log in with a combination of email and password :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 23:49 UTC, Felix45 commented on app/views/layouts/application.html.erb
- [ Required ] I think it would be better if you fixed this error in the `app/views/layouts/application.html.erb` file, it appears the line adding `tailwind css` to your project can not find the tailwind library in `app/assets/stylesheets/application.tailwind.css` I would like to suggest that you refactor line `8` to the following so that the file is added properly to the page. 

This is because the tailwind.css file in the `app/assets/stylesheets/` directory has the name `application.tailwind.css` not `tailwind.css`, please rectify this.

## Example code
```ruby
<% stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>
```

## Error in App
![Screenshot from 2023-05-20 02-25-30](https://github.com/limavfabio/MyRailsBlog/assets/16392046/6029e8ef-56ee-4657-bc86-b63515b36538)

2023-05-19 23:49 UTC, Felix45 commented on app/views/devise/registrations/new.html.erb
- [ Required ] Please consider styling your _sign-up_ and _login_ pages as provided in the wireframes for this project. The _sign up_ and _login_ forms should be centered on the page and the `submit` and `input` fields should have equal widths as shown in the wireframe below.

## Project wireframe
![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_login.png)

## Your design
![Screenshot from 2023-05-20 02-41-04](https://github.com/limavfabio/MyRailsBlog/assets/16392046/efdcc1a9-c1fa-472c-8cf0-46138fb2a941)

![Screenshot from 2023-05-20 02-41-58](https://github.com/limavfabio/MyRailsBlog/assets/16392046/37507016-0663-47d7-bc47-00da00dd13e8)

2023-05-20 19:32 UTC, AnselemOdims approved these changes
### Hi  @limavfabio 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 21:46 UTC, merged